dist: bionic
language: java
jdk: openjdk11

script:
  - echo "running standard tests"; ./gradlew test
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then echo "running operational tests"; ./gradlew testOperational; fi
